#!/usr/bin/env php
<?php

require_once('vendor/autoload.php');

define('SCRIPTS_ROOT', __DIR__);
define('LIBS_ROOT', SCRIPTS_ROOT . '/lib');

use Symfony\Component\Console\Application;

$application = new Application('Able', '0.1a');

$application->add(new Able\CommandSets\Sites\NewCommand());
$application->add(new Able\CommandSets\Sites\InstallCommand());
$application->add(new Able\CommandSets\Sites\DeployCommand());

$application->add(new Able\CommandSets\Core\UpdateCommand());
$application->add(new Able\CommandSets\Core\ConfigCommand());
$application->add(new Able\CommandSets\Core\PublishConfigCommand());

$application->add(new Able\CommandSets\Generate\EmptyModuleCommand());
$application->add(new Able\CommandSets\Generate\ModuleCommand());

$application->run();
