#!/usr/bin/env php
<?php

require_once('vendor/autoload.php');

define('SCRIPTS_ROOT', __DIR__);
define('LIBS_ROOT', SCRIPTS_ROOT . '/lib');

use Symfony\Component\Console\Application;

$application = new Application('Able', '0.2a');

// Register commands.
$application->add(new Able\CommandSets\Sites\InstallCommand());
$application->add(new Able\CommandSets\Sites\DeployCommand());

$application->add(new Able\CommandSets\Core\UpdateCommand());
$application->add(new Able\CommandSets\Core\ConfigCommand());
$application->add(new Able\CommandSets\Core\PublishConfigCommand());

$application->add(new Able\CommandSets\Generate\EmptyModuleCommand());
$application->add(new Able\CommandSets\Generate\ModuleCommand());

$application->add(new \Able\CommandSets\Node\InitGlobalKnowledgeCommand());
$application->add(new \Able\CommandSets\Node\GetCommand());
$application->add(new \Able\CommandSets\Node\SetCommand());

// Include all plugins.
foreach (glob(SCRIPTS_ROOT . '/plugins/*.php') as $file) {
	require_once($file);
}

// Run the application...
$application->run();
