<?php

/*
 * Helper files (like this one) are meant to contain utility functions used by the
 * module. While it is recommended to keep all functionality of a module inside an
 * xautoload library (for performance and organization purposes), sometimes it is
 * necessary to have helper functions in the global namespace.
 *
 * This file (and any file ending in ".inc" in this directory) is included automatically
 * by Able Core, so long as hook_ablecore() is implemented.
 */

function _MODULE_some_utility_function()
{
	// This function does nothing...
}
