<?php

/*
 * This file is used to contain hooks for whatever module the file is named after.
 * For example, if you are wanting to implement hooks added by the node module,
 * the name of this file should be "node.inc", and it should contain only hook
 * implementations for node-specific hooks.
 *
 * This file (and any file in this directory ending in ".inc") is automatically included
 * by Able Core (so long as hook_ablecore() is implemented).
 */

/**
 * Implements hook_module_hook()
 */
function MODULE_module_hook()
{
	// Nothing here on purpose...
}
